### ISSUE TITLE
PreciousStones - MCMMO

### ISSUE THREAD

**Issue by notrlySzymon** [mcMMO-Dev/mcMMO-Classic#4]
Dear Sir or Madam,

Hello. Some minutes ago I bought your plugin mcMMO. It does not work + it is doing a problems with PreciousStones. Please help me.

Yours faithfully,
Szymon Kupper

```
[00:57:46] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[00:57:46] [Server thread/WARN]: java.lang.NoSuchFieldError: FERN
[00:57:46] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadTreasures(TreasureConfig.java:275)
[00:57:46] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:95)
[00:57:46] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:38)
[00:57:46] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:44)
[00:57:46] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:374)
[00:57:46] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:134)
[00:57:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:57:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[00:57:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[00:57:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
[00:57:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
[00:57:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
[00:57:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
[00:57:46] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[00:57:46] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.6.0
[00:57:46] [Server thread/WARN]: [mcMMO] Skills.Taming.Call_Of_The_Wild.Ocelot.Item_Material is invalid!!
[00:57:46] [Server thread/WARN]: [mcMMO] Errors were found in config.yml! mcMMO was disabled!
[00:57:46] [Server thread/ERROR]: [mcMMO] Cannot read /home/nozofiles/s31049/server_files/plugins/mcMMO/experience.yml(File Permissions?)
[00:57:46] [Server thread/ERROR]: [mcMMO] Cannot read /home/nozofiles/s31049/server_files/plugins/mcMMO/repair.vanilla.yml(File Permissions?)
[00:57:46] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.6.0 (Is it up to date?)
java.lang.NullPointerException: null
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:234) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:421) [server.jar:git-Spigot-b78586d-f3356f1]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:188) [mcMMO-2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [server.jar:git-Spigot-b78586d-f3356f1]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [server.jar:git-Spigot-b78586d-f3356f1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [server.jar:git-Spigot-b78586d-f3356f1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```
```
[00:57:51] [Server thread/INFO]: [PreciousStones] Enabling PreciousStones v10.7.2
[00:57:52] [Server thread/INFO]: [PreciousStones] Version 10.7.2 loaded
[00:57:52] [Server thread/ERROR]: Error occurred while enabling PreciousStones v10.7.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/gmail/nossr50/mcMMO
	at net.sacredlabyrinth.Phaed.PreciousStones.managers.PermissionsManager.detectMcMMO(PermissionsManager.java:75) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.managers.PermissionsManager.<init>(PermissionsManager.java:58) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones.onEnable(PreciousStones.java:145) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [server.jar:git-Spigot-b78586d-f3356f1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [server.jar:git-Spigot-b78586d-f3356f1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [server.jar:git-Spigot-b78586d-f3356f1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [server.jar:git-Spigot-b78586d-f3356f1]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [server.jar:git-Spigot-b78586d-f3356f1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [server.jar:git-Spigot-b78586d-f3356f1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.mcMMO
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-b78586d-f3356f1]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_60]
	... 14 more
```

**Comment by notrlySzymon** [comment]
[00:57:45] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.6.0
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: WOODEN_SWORD
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: WOODEN_SHOVEL
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: WOODEN_PICKAXE
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: WOODEN_AXE
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: WOODEN_HOE
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: LAPIS_LAZULI
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: STONE_SHOVEL
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: GOLDEN_SWORD
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: GOLDEN_SHOVEL
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: GOLDEN_PICKAXE
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: GOLDEN_AXE
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: GOLDEN_HOE
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: GOLDEN_BOOTS
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: GOLDEN_HELMET
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: GOLDEN_LEGGINGS
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: GOLDEN_CHESTPLATE
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: IRON_SHOVEL
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: DIAMOND_SHOVEL
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: MUSIC_DISC_BLOCKS
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: MUSIC_DISC_CHIRP
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: MUSIC_DISC_FAR
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: MUSIC_DISC_MALL
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: MUSIC_DISC_MELLOHI
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: MUSIC_DISC_STAL
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: MUSIC_DISC_STRAD
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: MUSIC_DISC_WARD
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: MUSIC_DISC_11
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: MUSIC_DISC_WAIT
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: MUSIC_DISC_13
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: GUNPOWDER
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: CLOCK
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: COBWEB
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: MUSIC_DISC_13
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: MUSIC_DISC_CAT
[00:57:46] [Server thread/WARN]: [mcMMO] Invalid material: COCOA_BEANS
[00:57:46] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[00:57:46] [Server thread/WARN]: java.lang.NoSuchFieldError: FERN
[00:57:46] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadTreasures(TreasureConfig.java:275)
[00:57:46] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:95)
[00:57:46] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:38)
[00:57:46] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:44)
[00:57:46] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:374)
[00:57:46] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:134)
[00:57:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:57:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[00:57:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[00:57:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
[00:57:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
[00:57:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
[00:57:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
[00:57:46] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[00:57:46] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.6.0
[00:57:46] [Server thread/WARN]: [mcMMO] Skills.Taming.Call_Of_The_Wild.Ocelot.Item_Material is invalid!!
[00:57:46] [Server thread/WARN]: [mcMMO] Errors were found in config.yml! mcMMO was disabled!
[00:57:46] [Server thread/ERROR]: [mcMMO] Cannot read /home/nozofiles/s31049/server_files/plugins/mcMMO/experience.yml(File Permissions?)
[00:57:46] [Server thread/ERROR]: [mcMMO] Cannot read /home/nozofiles/s31049/server_files/plugins/mcMMO/repair.vanilla.yml(File Permissions?)
[00:57:46] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.6.0 (Is it up to date?)
java.lang.NullPointerException: null
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:234) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:421) [server.jar:git-Spigot-b78586d-f3356f1]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:188) [mcMMO-2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [server.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [server.jar:git-Spigot-b78586d-f3356f1]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [server.jar:git-Spigot-b78586d-f3356f1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [server.jar:git-Spigot-b78586d-f3356f1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]

**Comment by nossr50** [comment]
most likely your config files are bad, this is an ongoing issue and we will likely deploy a fix if that is the case

you can delete all the .yml files in /plugins/mcMMO/ as a temporary solution
