### ISSUE TITLE
Commands not working.

### ISSUE THREAD

**Issue by goldenkuky209** [mcMMO-Dev/mcMMO-Classic#48]
Hello, let me explain what is happening.
mcMMO-1.6.1
Minecraft version- 1.14.4
I downloaded mcMMO on my server and some commands like /mctop or /mcstats don't work.
In chat it sais: "An international error occurred while attempting to perform this command" or ?"Your previous command is still being processed. Please wait." and it never gets processed.
I did not change any of the files or permissions.
The plugins that im currently using on the server are:
-ChatColor2
-ChunkSpawnerLimiter
-KitPvP
-JumpPads
-EmeraldTools
-MoreItems
-OldCombatMechanics
-SpawnerSilk
-TabList
-CoreProtect
-LuckPerms
-WorldEdit
-NickNames
-AutoMessage
-AdvancedBan
-Votifier
-LaggRemover
-Multiverse-Core
-ProtocolLib
-VoidSpawn
-Wither
-AvancedPortals
-VotingPlugin
-Minepacks
-mcMMO
-Vault
-DragoItem
-UltaCosmetics
-Matrix
-Pwi (PerWorldInventory)
-HolographicDisplays
-QuickShop
-WorldGuard
-GUIShop
-AuctionHouse
-NetherPortal
-CratesPlus
-InfernalMobs
-Essentials
-Jobs
-BuycraftX
-ActionHealth
-DragonSlayer
-Shopkeepers
-EssentialsChat
-GriefPrevention
-StackMob
-EssentialsSpawn
-TitleManager
-RandomTP

**Comment by t00thpick1** [comment]
I need the error from your server log.

**Comment by GewoonYorick** [comment]
I have the same issue. Logs: 
```
[23:35:37 INFO]: shadoozo issued server command: /mcrank
[23:35:37 WARN]: [mcMMO] Task #233523 for mcMMO v2.1.207 generated an exception
java.lang.IllegalStateException: Unregistered scoreboard component
	at org.bukkit.craftbukkit.v1_18_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:159) ~[paper-1.18.1.jar:git-Paper-160]
	at org.bukkit.craftbukkit.v1_18_R1.scoreboard.CraftObjective.getScore(CraftObjective.java:136) ~[paper-1.18.1.jar:git-Paper-160]
	at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.acceptRankData(ScoreboardWrapper.java:618) ~[mcMMO.jar:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.showPlayerRankScoreboard(ScoreboardManager.java:411) ~[mcMMO.jar:?]
	at com.gmail.nossr50.runnables.commands.McrankCommandDisplayTask.displayBoard(McrankCommandDisplayTask.java:66) ~[mcMMO.jar:?]
	at com.gmail.nossr50.runnables.commands.McrankCommandDisplayTask.run(McrankCommandDisplayTask.java:35) ~[mcMMO.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-160]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-160]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-160]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-160]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-160]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-160]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-160]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
