### ISSUE TITLE
Scoreboard McMMO -> Spigot Errors

### ISSUE THREAD

**Issue by PancakePuncher** [mcMMO-Dev/mcMMO-Classic#50]
Hello,

I'm being thrown an exception error for "scoreboard" functions.

I've attempted updating all my plugins with no resolve. I did not have this error on a clean local test server, but that's not really an option for my current MP server.

This error appears in my console every time it seems any kind of function is preformed on McMMO it doesn't seem to be impacting the functionality of the Plugin except for the scoreboard."

Plugins I have installed:

[Server thread/INFO]: Plugins (27): CoreProtect, dynmap, WorldEdit, AngelChest, DangerousNether, SAML, BlockLocker, Lands, WorldBorder, ProtocolLib, ChestSort, WorldGuard, CubCustomDrops, BetterBookshelfs, mcMMO, UltraPermissions, mcMMOAction, Vault, InfernalMobs, Essentials, QuickShop, MythicMobs, BetterSleeping, EssentialsChat, EssentialsGeoIP, WorldGuardExtraFlags, PremiumVanish

Looking to get some assistance and insight on what my be causing this.

> [Server thread/WARN]: [mcMMO] Task #226123 for mcMMO v1.6.1 generated an exception

java.lang.IllegalStateException: Unregistered scoreboard component
        at org.bukkit.craftbukkit.v1_14_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:137) ~[spigot.jar:git-Spigot-56f8471-56118c6]
        at org.bukkit.craftbukkit.v1_14_R1.scoreboard.CraftObjective.getScore(CraftObjective.java:122) ~[spigot.jar:git-Spigot-56f8471-56118c6]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.updateSidebar(ScoreboardWrapper.java:448) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.access$000(ScoreboardWrapper.java:29) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper$ScoreboardQuickUpdate.run(ScoreboardWrapper.java:80) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-56f8471-56118c6]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022) [spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot.jar:git-Spigot-56f8471-56118c6]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by t00thpick1** [comment]
Interesting.  Do any of your other plugins affect scoreboards?

**Comment by PancakePuncher** [comment]
I'm pretty sure Premium Vanish does but I turned off the "Scoreboard" it creates.
