### ISSUE TITLE
A error while using mcmmo in paperspigot 1.9

### ISSUE THREAD

**Issue by LFMJUN** [mcMMO-Dev/mcMMO-Classic#52]
I used the lastest mcmmo file to install in my server.
The plugin didnt work. Please help me!
Here is the log.
`[17:42:23] [Server thread/INFO]: [mcMMO] Enabling mcMMO v2.1.111
[17:42:23] [Server thread/WARN]: [mcMMO] Invalid material: INK_SACK_BLUE
[17:42:23] [Server thread/WARN]: [mcMMO] Invalid material: INK_SACK_BROWN
[17:42:23] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[17:42:23] [Server thread/WARN]: java.lang.NoSuchFieldError: FERN
[17:42:23] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadTreasures(TreasureConfig.java:274)
[17:42:23] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:94)
[17:42:23] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:37)
[17:42:23] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:43)
[17:42:23] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:513)
[17:42:23] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:155)
[17:42:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[17:42:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[17:42:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[17:42:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[17:42:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[17:42:23] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411)
[17:42:23] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376)
[17:42:23] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331)
[17:42:23] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269)
[17:42:23] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[17:42:23] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[17:42:23] [Server thread/INFO]: [mcMMO] Disabling mcMMO v2.1.111
[17:42:23] [Server thread/WARN]: java.lang.NullPointerException
[17:42:23] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:334)
[17:42:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294)
[17:42:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364)
[17:42:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
[17:42:23] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:249)
[17:42:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[17:42:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[17:42:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[17:42:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[17:42:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[17:42:23] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411)
[17:42:23] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376)
[17:42:23] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331)
[17:42:23] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269)
[17:42:23] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[17:42:23] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[17:42:23] [Server thread/ERROR]: [mcMMO] Cannot read /root/sc/plugins/mcMMO/experience.yml(File Permissions?)
[17:42:23] [Server thread/ERROR]: [mcMMO] Cannot read /root/sc/plugins/mcMMO/repair.vanilla.yml(File Permissions?)
[17:42:23] [Server thread/ERROR]: Error occurred while disabling mcMMO v2.1.111 (Is it up to date?)
java.lang.NullPointerException
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:366) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[aaaa.jar:git-Spigot-d20369f-7fc5cd8]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [aaaa.jar:git-Spigot-d20369f-7fc5cd8]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [aaaa.jar:git-Spigot-d20369f-7fc5cd8]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:249) [mcMMO%20(1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [aaaa.jar:git-Spigot-d20369f-7fc5cd8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [aaaa.jar:git-Spigot-d20369f-7fc5cd8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [aaaa.jar:git-Spigot-d20369f-7fc5cd8]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [aaaa.jar:git-Spigot-d20369f-7fc5cd8]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [aaaa.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [aaaa.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [aaaa.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [aaaa.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [aaaa.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [aaaa.jar:git-Spigot-d20369f-7fc5cd8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`
Thanks so much for helping me!

**Comment by Draycia** [comment]
![image](https://user-images.githubusercontent.com/15833072/71075275-9cc0fd00-2138-11ea-8700-d6116a43d0cc.png)

**Comment by LFMJUN** [comment]
So I cant use this plugin in 1.9 server right?

**Comment by Draycia** [comment]
You'll have to use an older build of classic meant for 1.9 in order to run mcmmo on 1.9

**Comment by LFMJUN** [comment]
Can you help me to find it?

**Comment by electronicboy** [comment]
https://www.spigotmc.org/resources/official-mcmmo-classic.2445/
Read the description...

**Comment by LFMJUN** [comment]
SpigotMC - High Performance Minecraft - Error
You do not have permission to view this page or perform this action.

**Comment by Draycia** [comment]
Those links are to updates for the plugin, you must purchase the plugin before you can use those links.

**Comment by LFMJUN** [comment]
I havent brought this plugin. I dont have enough money yet. :(

**Comment by Draycia** [comment]
You'll have to go through the commits and find the last one for 1.9 and compile it then

**Comment by LFMJUN** [comment]
Ok thanks. Another question. Which version start to have the bossbar?

**Comment by LFMJUN** [comment]
Thank you so much for helping me!

**Comment by Momshroom** [comment]
The boss bars show up in the overhaul version of Mcmmo.  2.----

**Comment by LFMJUN** [comment]
Thanks a lot！
