### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by TheCanadian529** [mcMMO-Dev/mcMMO-Classic#9]
When running any command this is what I get. Just downloaded the latest version of mcmmo frim the spigot page and am running 1.13.2 spigot. 

Any help with this would be awesome. 

"null
org.bukkit.command.CommandException: Cannot execute command 'mcmmo' in plugin mcMMO v1.6.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]"

Thanks,

**Comment by TheCanadian529** [comment]
I re-downloaded 1.6.0

and this is what I got now.

"[14:36:18 ERROR]: Error occurred while disabling mcMMO v1.6.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:198) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at com.gmail.nossr50.config.ConfigLoader.validate(ConfigLoader.java:67) ~[?:?]
        at com.gmail.nossr50.config.Config.<init>(Config.java:23) ~[?:?]
        at com.gmail.nossr50.config.Config.getInstance(Config.java:28) ~[?:?]
        at com.gmail.nossr50.locale.LocaleLoader.initialize(LocaleLoader.java:80) ~[?:?]
        at com.gmail.nossr50.locale.LocaleLoader.getString(LocaleLoader.java:33) ~[?:?]
        at com.gmail.nossr50.locale.LocaleLoader.getString(LocaleLoader.java:21) ~[?:?]
        at com.gmail.nossr50.datatypes.skills.ToolType.<clinit>(ToolType.java:10) ~[?:?]
        at com.gmail.nossr50.datatypes.skills.SkillType.<clinit>(SkillType.java:42) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.getMaxChance(AdvancedConfig.java:693) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.validateKeys(AdvancedConfig.java:48) ~[?:?]
        at com.gmail.nossr50.config.ConfigLoader.validate(ConfigLoader.java:62) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.<init>(AdvancedConfig.java:22) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.getInstance(AdvancedConfig.java:27) ~[?:?]
        at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:376) ~[?:?]
        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:134) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) ~[?:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) ~[?:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at com.gmail.nossr50.datatypes.skills.SkillType.values(SkillType.java:38) ~[?:?]
        at com.gmail.nossr50.datatypes.skills.SkillType.bySecondaryAbility(SkillType.java:197) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.getMaxChance(AdvancedConfig.java:693) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.validateKeys(AdvancedConfig.java:48) ~[?:?]
        at com.gmail.nossr50.config.ConfigLoader.validate(ConfigLoader.java:62) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.<init>(AdvancedConfig.java:22) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.getInstance(AdvancedConfig.java:27) ~[?:?]
        at com.gmail.nossr50.skills.alchemy.Alchemy.<clinit>(Alchemy.java:51) ~[?:?]
        ... 43 more"

**Comment by TheCanadian529** [comment]
[14:36:18 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[14:36:18 WARN]: java.lang.IllegalAccessError: tried to access class com.gmail.nossr50.datatypes.skills.SkillType$1 from class com.gmail.nossr50.datatypes.skills.SkillType
[14:36:18 WARN]:        at com.gmail.nossr50.datatypes.skills.SkillType.isChildSkill(SkillType.java:186)
[14:36:18 WARN]:        at com.gmail.nossr50.datatypes.skills.SkillType.<clinit>(SkillType.java:76)
[14:36:18 WARN]:        at com.gmail.nossr50.config.AdvancedConfig.getMaxChance(AdvancedConfig.java:693)
[14:36:18 WARN]:        at com.gmail.nossr50.config.AdvancedConfig.validateKeys(AdvancedConfig.java:48)
[14:36:18 WARN]:        at com.gmail.nossr50.config.ConfigLoader.validate(ConfigLoader.java:62)
[14:36:18 WARN]:        at com.gmail.nossr50.config.AdvancedConfig.<init>(AdvancedConfig.java:22)
[14:36:18 WARN]:        at com.gmail.nossr50.config.AdvancedConfig.getInstance(AdvancedConfig.java:27)
[14:36:18 WARN]:        at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:376)
[14:36:18 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:134)
[14:36:18 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[14:36:18 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[14:36:18 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[14:36:18 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
[14:36:18 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318)
[14:36:18 WARN]:        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380)
[14:36:18 WARN]:        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[14:36:18 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[14:36:18 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:36:18 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
[14:36:18 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702)
[14:36:18 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641)
[14:36:18 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476)
[14:36:18 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[14:36:18 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:36:18 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[14:36:18 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:36:18 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:36:18 WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[14:36:18 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895)
[14:36:18 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[14:36:18 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830)
[14:36:18 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728)
[14:36:18 WARN]:        at java.lang.Thread.run(Unknown Source)
